/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz;

import Logica.Interprete;
import java.util.Arrays;
import javax.swing.ImageIcon;

/**
 *
 * @author NATA
 */
public class Analizador extends javax.swing.JFrame {
    
    Interprete interprete;
    Resultados ventanaRes;

    /**
     * Creates new form Analizador
     */
    public Analizador() {
        interprete = new Interprete();
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLTitulo = new javax.swing.JLabel();
        JLEnunciado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTATexto = new javax.swing.JTextArea();
        JBAnalizar = new javax.swing.JButton();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Lexico");
        setBounds(new java.awt.Rectangle(300, 150, 500, 450));
        setPreferredSize(new java.awt.Dimension(500, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        JLTitulo.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        JLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLTitulo.setText("Analizador Lexico");
        getContentPane().add(JLTitulo);
        JLTitulo.setBounds(0, 30, 490, 50);

        JLEnunciado.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        JLEnunciado.setText("Ingrese el texto que desea analizar:");
        getContentPane().add(JLEnunciado);
        JLEnunciado.setBounds(30, 140, 420, 14);

        JTATexto.setColumns(20);
        JTATexto.setRows(5);
        jScrollPane1.setViewportView(JTATexto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 180, 360, 170);

        JBAnalizar.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        JBAnalizar.setText("Analizar");
        JBAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(JBAnalizar);
        JBAnalizar.setBounds(170, 360, 120, 40);

        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(JLFondo);
        JLFondo.setBounds(0, 0, 493, 420);
        JLFondo.getAccessibleContext().setAccessibleName("JLFondo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAnalizarActionPerformed
        // TODO add your handling code here:
        String texto = JTATexto.getText();
        texto = texto.replace("\n", " ");
        String[] separadas = texto.split(" ");
        int[] resultados = interprete.verificar(separadas);
        ventanaRes = new Resultados();
        ventanaRes.llenarTabla(separadas, resultados);
        ventanaRes.setVisible(true);
    }//GEN-LAST:event_JBAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAnalizar;
    private javax.swing.JLabel JLEnunciado;
    private javax.swing.JLabel JLFondo;
    private javax.swing.JLabel JLTitulo;
    private javax.swing.JTextArea JTATexto;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
